ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin','staff','trainer') NOT NULL DEFAULT 'user';
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `members` (`id` int AUTO_INCREMENT NOT NULL, `code` varchar(32) NOT NULL, `name` varchar(150) NOT NULL, `email` varchar(320) NOT NULL, `phone` varchar(20) NOT NULL, `gender` enum('Nam','Nữ','Khác') NOT NULL, `birthDate` date NOT NULL, `address` text NOT NULL, `status` enum('active','inactive') NOT NULL DEFAULT 'active', `joinedAt` date NOT NULL, `emergencyContact` varchar(255) NOT NULL, `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `members_id` PRIMARY KEY(`id`), CONSTRAINT `members_code_unique` UNIQUE(`code`));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `plans` (`id` int AUTO_INCREMENT NOT NULL, `name` varchar(120) NOT NULL, `description` text NOT NULL, `durationDays` int NOT NULL, `price` decimal(12,0) NOT NULL, `status` enum('active','inactive') NOT NULL DEFAULT 'active', `popular` int NOT NULL DEFAULT 0, CONSTRAINT `plans_id` PRIMARY KEY(`id`));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `trainers` (`id` int AUTO_INCREMENT NOT NULL, `name` varchar(150) NOT NULL, `email` varchar(320) NOT NULL, `phone` varchar(20) NOT NULL, `specialty` varchar(150) NOT NULL, `experience` varchar(50) NOT NULL, `status` enum('active','inactive') NOT NULL DEFAULT 'active', CONSTRAINT `trainers_id` PRIMARY KEY(`id`));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `memberships` (`id` int AUTO_INCREMENT NOT NULL, `memberId` int NOT NULL, `planId` int NOT NULL, `startDate` date NOT NULL, `endDate` date NOT NULL, `amount` decimal(12,0) NOT NULL, `status` enum('active','expired','cancelled') NOT NULL DEFAULT 'active', `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `memberships_id` PRIMARY KEY(`id`), CONSTRAINT `memberships_member_fk` FOREIGN KEY (`memberId`) REFERENCES `members`(`id`), CONSTRAINT `memberships_plan_fk` FOREIGN KEY (`planId`) REFERENCES `plans`(`id`));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `schedules` (`id` int AUTO_INCREMENT NOT NULL, `title` varchar(150) NOT NULL, `memberId` int NOT NULL, `trainerId` int NOT NULL, `startAt` datetime NOT NULL, `endAt` datetime NOT NULL, `type` enum('PT','Group') NOT NULL, `status` enum('scheduled','completed','cancelled') NOT NULL DEFAULT 'scheduled', `note` text, CONSTRAINT `schedules_id` PRIMARY KEY(`id`), CONSTRAINT `schedules_member_fk` FOREIGN KEY (`memberId`) REFERENCES `members`(`id`), CONSTRAINT `schedules_trainer_fk` FOREIGN KEY (`trainerId`) REFERENCES `trainers`(`id`));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `checkins` (`id` int AUTO_INCREMENT NOT NULL, `memberId` int NOT NULL, `checkInAt` timestamp NOT NULL, `checkOutAt` timestamp NULL, `durationMinutes` int NULL, `recordedBy` int NOT NULL, CONSTRAINT `checkins_id` PRIMARY KEY(`id`), CONSTRAINT `checkins_member_fk` FOREIGN KEY (`memberId`) REFERENCES `members`(`id`), CONSTRAINT `checkins_recorder_fk` FOREIGN KEY (`recordedBy`) REFERENCES `users`(`id`));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `payments` (`id` int AUTO_INCREMENT NOT NULL, `memberId` int NOT NULL, `membershipId` int NULL, `amount` decimal(12,0) NOT NULL, `method` enum('cash','transfer','card') NOT NULL, `status` enum('paid','pending','refunded') NOT NULL DEFAULT 'paid', `reference` varchar(64) NOT NULL, `paidAt` timestamp NOT NULL, `createdBy` int NOT NULL, CONSTRAINT `payments_id` PRIMARY KEY(`id`), CONSTRAINT `payments_reference_unique` UNIQUE(`reference`), CONSTRAINT `payments_member_fk` FOREIGN KEY (`memberId`) REFERENCES `members`(`id`), CONSTRAINT `payments_membership_fk` FOREIGN KEY (`membershipId`) REFERENCES `memberships`(`id`), CONSTRAINT `payments_creator_fk` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`));
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `auditLogs` (`id` varchar(64) NOT NULL, `actorId` int NOT NULL, `action` varchar(32) NOT NULL, `resource` varchar(64) NOT NULL, `resourceId` int NULL, `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `auditLogs_id` PRIMARY KEY(`id`), CONSTRAINT `auditLogs_actor_fk` FOREIGN KEY (`actorId`) REFERENCES `users`(`id`));
