import { Router, type NextFunction, type Request, type Response } from "express";
import { SignJWT, jwtVerify } from "jose";
import { z } from "zod";
import { gymStore, type GymUser, type Role } from "./gymData";
import { persistGymStoreToDatabase } from "./gymSqlPersistence";

const jwtSecret = new TextEncoder().encode(process.env.JWT_SECRET || "gymflow-demo-secret-change-me");
const api = Router();

api.use((req, res, next) => {
  if (["POST", "PATCH", "DELETE"].includes(req.method) && !req.path.startsWith("/auth/")) {
    const send = res.send.bind(res);
    res.send = ((body?: unknown) => {
      if (res.statusCode >= 200 && res.statusCode < 300) {
        if (process.env.DATABASE_URL) {
          void persistGymStoreToDatabase().then(() => {
            try { gymStore.save(); } catch (error) { console.warn("[Store] MariaDB saved the change, but the local JSON backup could not be updated:", error); }
            send(body as never);
          }).catch(next);
          return res;
        }
        gymStore.save();
      }
      return send(body as never);
    }) as typeof res.send;
  }
  next();
});

type AuthedRequest = Request & { user?: GymUser };
const ok = (res: Response, data: unknown, meta?: Record<string, unknown>) => res.json({ success: true, data, ...(meta ? { meta } : {}) });
const created = (res: Response, data: unknown) => res.status(201).json({ success: true, data });
const fail = (res: Response, status: number, code: string, message: string, details?: unknown) => res.status(status).json({ success: false, error: { code, message, ...(details ? { details } : {}) } });
const asyncRoute = (handler: (req: AuthedRequest, res: Response, next: NextFunction) => Promise<unknown> | unknown) => (req: Request, res: Response, next: NextFunction) => Promise.resolve(handler(req as AuthedRequest, res, next)).catch(next);

function signToken(user: GymUser) {
  return new SignJWT({ sub: String(user.id), role: user.role, name: user.name, email: user.email }).setProtectedHeader({ alg: "HS256" }).setIssuedAt().setExpirationTime("12h").sign(jwtSecret);
}

const auth = asyncRoute(async (req, res, next) => {
  const token = req.headers.authorization?.replace(/^Bearer\s+/i, "") || req.cookies?.gymflow_token;
  if (!token) return fail(res, 401, "UNAUTHORIZED", "Vui lòng đăng nhập để tiếp tục");
  try {
    const { payload } = await jwtVerify(token, jwtSecret);
    const user = gymStore.users.find(item => item.id === Number(payload.sub));
    if (!user) return fail(res, 401, "UNAUTHORIZED", "Phiên đăng nhập không hợp lệ");
    req.user = user;
    next();
  } catch {
    return fail(res, 401, "UNAUTHORIZED", "Token đã hết hạn hoặc không hợp lệ");
  }
});
const allow = (...roles: Role[]) => (req: AuthedRequest, res: Response, next: NextFunction) => req.user && roles.includes(req.user.role) ? next() : fail(res, 403, "FORBIDDEN", "Bạn không có quyền thực hiện thao tác này");

const pageQuery = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(10), search: z.string().optional(), status: z.string().optional(), sortBy: z.string().optional(), sortOrder: z.enum(["asc", "desc"]).default("desc") });
function paginate<T>(items: T[], query: z.infer<typeof pageQuery>) {
  const start = (query.page - 1) * query.limit;
  const sorted = query.sortBy ? [...items].sort((left, right) => { const a = String((left as Record<string, unknown>)[query.sortBy!] ?? ""); const b = String((right as Record<string, unknown>)[query.sortBy!] ?? ""); const result = a.localeCompare(b, "vi", { numeric: true }); return query.sortOrder === "asc" ? result : -result; }) : items;
  return { rows: sorted.slice(start, start + query.limit), meta: { page: query.page, limit: query.limit, total: sorted.length, totalPages: Math.ceil(sorted.length / query.limit), sortBy: query.sortBy, sortOrder: query.sortOrder } };
}
const parseId = (req: Request, res: Response) => { const id = Number(req.params.id); if (!Number.isInteger(id) || id < 1) { fail(res, 400, "INVALID_ID", "ID không hợp lệ"); return null; } return id; };
const validWindow = (startAt: string, endAt: string) => { const start = new Date(startAt); const end = new Date(endAt); return Number.isFinite(start.getTime()) && Number.isFinite(end.getTime()) && start < end; };
const trainerIdForUser = (user: GymUser) => gymStore.trainers.find(item => item.email.toLowerCase() === user.email.toLowerCase())?.id;
const trainerMemberIds = (user: GymUser) => { const trainerId = trainerIdForUser(user); return new Set(gymStore.schedules.filter(schedule => schedule.trainerId === trainerId).map(schedule => schedule.memberId)); };
const trainerMemberView = (member: ReturnType<typeof gymStore.enrichMember>) => { const { email, gender, birthDate, address, emergencyContact, ...safeMember } = member; return safeMember; };
const trainerScope = (req: AuthedRequest, res: Response, trainerId: number) => { if (req.user?.role !== "trainer" || trainerIdForUser(req.user) === trainerId) return true; fail(res, 403, "FORBIDDEN", "Trainer chỉ được quản lý lịch của chính mình"); return false; };

api.get("/health", (_req, res) => ok(res, { status: "ok", service: "gymflow-api", mode: process.env.DATABASE_URL ? "mysql-persistence" : "local-file-persistence", timestamp: new Date().toISOString() }));
api.post("/auth/login", asyncRoute(async (req, res) => {
  const input = z.object({ email: z.string().email(), password: z.string().min(6) }).safeParse(req.body);
  if (!input.success) return fail(res, 400, "VALIDATION_ERROR", "Email hoặc mật khẩu không hợp lệ", input.error.issues);
  const user = gymStore.users.find(item => item.email.toLowerCase() === input.data.email.toLowerCase() && item.password === input.data.password);
  if (!user) return fail(res, 401, "INVALID_CREDENTIALS", "Email hoặc mật khẩu không đúng");
  user.lastSignedIn = new Date().toISOString();
  return ok(res, { token: await signToken(user), user: { ...user, password: undefined } });
}));
api.use(auth);
api.get("/auth/me", (req: AuthedRequest, res) => ok(res, { ...req.user, password: undefined }));
api.post("/auth/logout", (_req, res) => ok(res, { loggedOut: true }));

api.get("/dashboard/summary", allow("admin"), (_req, res) => ok(res, gymStore.dashboard()));
api.get("/dashboard/revenue", allow("admin"), (_req, res) => ok(res, gymStore.dashboard().revenueByMonth));
api.get("/dashboard/activity", allow("admin"), (_req, res) => ok(res, gymStore.checkins.slice(0, 8).map(item => ({ ...item, member: gymStore.members.find(member => member.id === item.memberId) }))));

api.get("/members/me", (req: AuthedRequest, res) => { if (req.user?.role !== "member" || !req.user.memberId) return fail(res, 403, "FORBIDDEN", "Tài khoản chưa được liên kết với hội viên"); const member = gymStore.members.find(item => item.id === req.user!.memberId); return member ? ok(res, gymStore.enrichMember(member)) : fail(res, 404, "NOT_FOUND", "Không tìm thấy hội viên"); });
api.get("/members", (req: AuthedRequest, res) => { const query = pageQuery.parse(req.query); let rows: Array<Record<string, any>> = gymStore.members.map(item => gymStore.enrichMember(item)); if (req.user?.role === "member") rows = rows.filter(item => item.id === req.user!.memberId); if (req.user?.role === "trainer") { const assignedMembers = trainerMemberIds(req.user); rows = rows.filter(item => assignedMembers.has(item.id)).map(item => trainerMemberView(item as ReturnType<typeof gymStore.enrichMember>)); } if (query.search) { const term = query.search.toLowerCase(); rows = rows.filter(item => [item.name, item.email, item.phone, item.code].some(value => String(value ?? "").toLowerCase().includes(term))); } if (query.status) rows = rows.filter(item => item.status === query.status); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/members/:id", (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; if (req.user?.role === "member" && req.user.memberId !== id) return fail(res, 403, "FORBIDDEN", "Bạn chỉ được xem hồ sơ của mình"); if (req.user?.role === "trainer" && !trainerMemberIds(req.user).has(id)) return fail(res, 403, "FORBIDDEN", "Trainer chỉ được xem hội viên được phân công"); const item = gymStore.members.find(member => member.id === id); if (!item) return fail(res, 404, "NOT_FOUND", "Không tìm thấy hội viên"); const detail = gymStore.enrichMember(item); return ok(res, req.user?.role === "trainer" ? trainerMemberView(detail) : detail); });
const memberInput = z.object({ name: z.string().min(2), email: z.string().email(), phone: z.string().min(9), gender: z.enum(["Nam", "Nữ", "Khác"]), birthDate: z.string(), address: z.string().min(3), status: z.enum(["active", "inactive"]).default("active"), emergencyContact: z.string().min(3) });
const memberCreateInput = memberInput.extend({ password: z.string().min(6) });
api.post("/members", allow("admin"), (req: AuthedRequest, res) => { const parsed = memberCreateInput.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu hội viên không hợp lệ", parsed.error.issues); const email = parsed.data.email.toLowerCase(); if (gymStore.users.some(user => user.email.toLowerCase() === email) || gymStore.members.some(member => member.email.toLowerCase() === email)) return fail(res, 409, "EMAIL_EXISTS", "Email đã được dùng cho tài khoản khác"); const { password, ...profile } = parsed.data; const member = { id: gymStore.nextId("members"), code: `GYM-${String(gymStore.nextIds.members - 1).padStart(3, "0")}`, joinedAt: new Date().toISOString().slice(0, 10), ...profile }; gymStore.members.unshift(member); gymStore.users.push({ id: gymStore.nextId("users"), name: member.name, email: member.email, password, role: "member", memberId: member.id, avatar: member.name.split(" ").map(part => part[0]).slice(-2).join("").toUpperCase() }); gymStore.log(req.user!.id, "CREATE", "members", member.id); return created(res, gymStore.enrichMember(member)); });
api.patch("/members/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const parsed = memberInput.partial().safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu cập nhật không hợp lệ", parsed.error.issues); const member = gymStore.members.find(item => item.id === id); if (!member) return fail(res, 404, "NOT_FOUND", "Không tìm thấy hội viên"); if (parsed.data.email && gymStore.users.some(user => user.memberId !== id && user.email.toLowerCase() === parsed.data.email!.toLowerCase())) return fail(res, 409, "EMAIL_EXISTS", "Email đã được dùng cho tài khoản khác"); Object.assign(member, parsed.data); const account = gymStore.users.find(user => user.memberId === id); if (account) { account.name = member.name; account.email = member.email; account.avatar = member.name.split(" ").map(part => part[0]).slice(-2).join("").toUpperCase(); } gymStore.log(req.user!.id, "UPDATE", "members", id); return ok(res, gymStore.enrichMember(member)); });
api.delete("/members/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const index = gymStore.members.findIndex(item => item.id === id); if (index < 0) return fail(res, 404, "NOT_FOUND", "Không tìm thấy hội viên"); gymStore.members.splice(index, 1); gymStore.users = gymStore.users.filter(user => user.memberId !== id); gymStore.log(req.user!.id, "DELETE", "members", id); return res.status(204).send(); });

api.get("/plans", (req, res) => { const query = pageQuery.parse(req.query); let rows = gymStore.plans; if (query.search) rows = rows.filter(item => `${item.name} ${item.description}`.toLowerCase().includes(query.search!.toLowerCase())); if (query.status) rows = rows.filter(item => item.status === query.status); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/plans/:id", (req, res) => { const id = parseId(req, res); if (!id) return; const item = gymStore.plans.find(plan => plan.id === id); return item ? ok(res, item) : fail(res, 404, "NOT_FOUND", "Không tìm thấy gói tập"); });
const planInput = z.object({ name: z.string().min(2), description: z.string().min(5), durationDays: z.coerce.number().int().positive(), price: z.coerce.number().positive(), status: z.enum(["active", "inactive"]).default("active"), popular: z.boolean().optional() });
api.post("/plans", allow("admin"), (req: AuthedRequest, res) => { const parsed = planInput.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu gói tập không hợp lệ", parsed.error.issues); const plan = { id: gymStore.nextId("plans"), ...parsed.data }; gymStore.plans.push(plan); gymStore.log(req.user!.id, "CREATE", "plans", plan.id); return created(res, plan); });
api.patch("/plans/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const parsed = planInput.partial().safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu cập nhật không hợp lệ", parsed.error.issues); const plan = gymStore.plans.find(item => item.id === id); if (!plan) return fail(res, 404, "NOT_FOUND", "Không tìm thấy gói tập"); Object.assign(plan, parsed.data); gymStore.log(req.user!.id, "UPDATE", "plans", id); return ok(res, plan); });
api.delete("/plans/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const index = gymStore.plans.findIndex(item => item.id === id); if (index < 0) return fail(res, 404, "NOT_FOUND", "Không tìm thấy gói tập"); gymStore.plans.splice(index, 1); gymStore.log(req.user!.id, "DELETE", "plans", id); return res.status(204).send(); });

api.get("/memberships", (req: AuthedRequest, res) => { const query = pageQuery.parse(req.query); let rows: Array<Record<string, any>> = gymStore.memberships.map(item => ({ ...item, member: gymStore.members.find(member => member.id === item.memberId), plan: gymStore.plans.find(plan => plan.id === item.planId) })); if (req.user?.role === "member") rows = rows.filter(item => item.memberId === req.user!.memberId); if (req.user?.role === "trainer") { const assignedMembers = trainerMemberIds(req.user); rows = rows.filter(item => assignedMembers.has(item.memberId)).map(item => ({ ...item, member: item.member ? trainerMemberView(gymStore.enrichMember(item.member)) : undefined })); } if (query.search) rows = rows.filter(item => item.member?.name.toLowerCase().includes(query.search!.toLowerCase()) || item.plan?.name.toLowerCase().includes(query.search!.toLowerCase())); if (query.status) rows = rows.filter(item => item.status === query.status); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/memberships/:id", (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const item = gymStore.memberships.find(membership => membership.id === id); if (!item) return fail(res, 404, "NOT_FOUND", "Không tìm thấy đăng ký gói"); if (req.user?.role === "member" && item.memberId !== req.user.memberId) return fail(res, 403, "FORBIDDEN", "Bạn chỉ được xem đăng ký gói của mình"); if (req.user?.role === "trainer" && !trainerMemberIds(req.user).has(item.memberId)) return fail(res, 403, "FORBIDDEN", "Trainer chỉ được xem đăng ký của hội viên được phân công"); const member = gymStore.members.find(profile => profile.id === item.memberId); return ok(res, { ...item, member: member && req.user?.role === "trainer" ? trainerMemberView(gymStore.enrichMember(member)) : member, plan: gymStore.plans.find(plan => plan.id === item.planId) }); });
const membershipInput = z.object({ memberId: z.coerce.number().int().positive().optional(), planId: z.coerce.number().int().positive(), startDate: z.string(), status: z.enum(["active", "expired", "cancelled"]).default("active") });
api.post("/memberships", allow("admin", "member"), (req: AuthedRequest, res) => { const parsed = membershipInput.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu đăng ký gói không hợp lệ", parsed.error.issues); const memberId = req.user?.role === "member" ? req.user.memberId : parsed.data.memberId; if (!memberId) return fail(res, 400, "VALIDATION_ERROR", "Cần chọn hội viên"); const member = gymStore.members.find(item => item.id === memberId); const plan = gymStore.plans.find(item => item.id === parsed.data.planId && item.status === "active"); if (!plan || !member) return fail(res, 409, "BUSINESS_CONFLICT", "Hội viên hoặc gói tập không tồn tại/không hoạt động"); if (req.user?.role === "member" && member.status !== "active") return fail(res, 403, "FORBIDDEN", "Hội viên đã tạm dừng"); if (req.user?.role === "member" && parsed.data.startDate < new Date().toISOString().slice(0, 10)) return fail(res, 400, "INVALID_START_DATE", "Ngày bắt đầu không được ở quá khứ"); if (req.user?.role === "member" && gymStore.memberships.some(item => item.memberId === member.id && item.status === "active" && item.endDate >= parsed.data.startDate)) return fail(res, 409, "MEMBERSHIP_OVERLAP", "Gói mới không được trùng thời hạn gói đang có"); const end = new Date(parsed.data.startDate); end.setDate(end.getDate() + plan.durationDays); const membership = { id: gymStore.nextId("memberships"), memberId: member.id, planId: plan.id, startDate: parsed.data.startDate, endDate: end.toISOString().slice(0, 10), amount: plan.price, status: req.user?.role === "member" ? "active" as const : parsed.data.status }; gymStore.memberships.unshift(membership); gymStore.log(req.user!.id, "CREATE", "memberships", membership.id); return created(res, { ...membership, member, plan }); });
api.patch("/memberships/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const parsed = z.object({ status: z.enum(["active", "expired", "cancelled"]) }).safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Trạng thái không hợp lệ"); const membership = gymStore.memberships.find(item => item.id === id); if (!membership) return fail(res, 404, "NOT_FOUND", "Không tìm thấy đăng ký gói"); membership.status = parsed.data.status; gymStore.log(req.user!.id, "UPDATE", "memberships", id); return ok(res, membership); });

api.get("/trainers", (req: AuthedRequest, res) => { const query = pageQuery.parse(req.query); let rows = req.user?.role === "trainer" ? gymStore.trainers.filter(item => item.id === trainerIdForUser(req.user!)) : gymStore.trainers; if (query.search) rows = rows.filter(item => `${item.name} ${item.specialty} ${item.email}`.toLowerCase().includes(query.search!.toLowerCase())); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/trainers/:id", (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; if (req.user?.role === "trainer" && !trainerScope(req, res, id)) return; const item = gymStore.trainers.find(trainer => trainer.id === id); return item ? ok(res, item) : fail(res, 404, "NOT_FOUND", "Không tìm thấy huấn luyện viên"); });
const trainerInput = z.object({ name: z.string().min(2), email: z.string().email(), phone: z.string().min(9), specialty: z.string().min(3), experience: z.string().min(1), status: z.enum(["active", "inactive"]).default("active") });
api.post("/trainers", allow("admin"), (req: AuthedRequest, res) => { const parsed = trainerInput.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu huấn luyện viên không hợp lệ", parsed.error.issues); const trainer = { id: gymStore.nextId("trainers"), ...parsed.data }; gymStore.trainers.push(trainer); gymStore.log(req.user!.id, "CREATE", "trainers", trainer.id); return created(res, trainer); });
api.patch("/trainers/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const parsed = trainerInput.partial().safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu cập nhật không hợp lệ", parsed.error.issues); const trainer = gymStore.trainers.find(item => item.id === id); if (!trainer) return fail(res, 404, "NOT_FOUND", "Không tìm thấy huấn luyện viên"); Object.assign(trainer, parsed.data); gymStore.log(req.user!.id, "UPDATE", "trainers", id); return ok(res, trainer); });
api.delete("/trainers/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; if (gymStore.schedules.some(item => item.trainerId === id && item.status === "scheduled")) return fail(res, 409, "TRAINER_HAS_SCHEDULE", "Không thể xóa huấn luyện viên còn lịch tập"); const index = gymStore.trainers.findIndex(item => item.id === id); if (index < 0) return fail(res, 404, "NOT_FOUND", "Không tìm thấy huấn luyện viên"); gymStore.trainers.splice(index, 1); gymStore.log(req.user!.id, "DELETE", "trainers", id); return res.status(204).send(); });

api.get("/schedules", (req: AuthedRequest, res) => { const query = pageQuery.parse(req.query); let rows: Array<Record<string, any>> = gymStore.schedules.map(item => ({ ...item, member: gymStore.members.find(member => member.id === item.memberId), trainer: gymStore.trainers.find(trainer => trainer.id === item.trainerId) })); if (req.user?.role === "member") rows = rows.filter(item => item.memberId === req.user!.memberId); if (req.user?.role === "trainer") { const trainerId = trainerIdForUser(req.user); rows = rows.filter(item => item.trainerId === trainerId).map(item => ({ ...item, member: item.member ? trainerMemberView(gymStore.enrichMember(item.member)) : undefined })); } if (query.search) rows = rows.filter(item => `${item.title} ${item.member?.name} ${item.trainer?.name}`.toLowerCase().includes(query.search!.toLowerCase())); if (query.status) rows = rows.filter(item => item.status === query.status); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/schedules/:id", (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const item = gymStore.schedules.find(schedule => schedule.id === id); if (!item) return fail(res, 404, "NOT_FOUND", "Không tìm thấy lịch tập"); if (req.user?.role === "member" && item.memberId !== req.user.memberId) return fail(res, 403, "FORBIDDEN", "Bạn chỉ được xem lịch tập của mình"); if (req.user?.role === "trainer" && !trainerScope(req, res, item.trainerId)) return; const member = gymStore.members.find(profile => profile.id === item.memberId); return ok(res, { ...item, member: member && req.user?.role === "trainer" ? trainerMemberView(gymStore.enrichMember(member)) : member, trainer: gymStore.trainers.find(trainer => trainer.id === item.trainerId) }); });
const scheduleInput = z.object({ title: z.string().min(2), memberId: z.coerce.number().int().positive(), trainerId: z.coerce.number().int().positive(), startAt: z.string(), endAt: z.string(), type: z.enum(["PT", "Group"]), status: z.enum(["scheduled", "completed", "cancelled"]).default("scheduled"), note: z.string().default("") });
api.post("/schedules", allow("admin", "trainer"), (req: AuthedRequest, res) => { const parsed = scheduleInput.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu lịch tập không hợp lệ", parsed.error.issues); if (!validWindow(parsed.data.startAt, parsed.data.endAt)) return fail(res, 400, "INVALID_TIME_WINDOW", "Thời gian bắt đầu phải trước thời gian kết thúc"); if (!trainerScope(req, res, parsed.data.trainerId)) return; const overlap = gymStore.schedules.some(item => item.trainerId === parsed.data.trainerId && item.status === "scheduled" && new Date(parsed.data.startAt) < new Date(item.endAt) && new Date(parsed.data.endAt) > new Date(item.startAt)); if (overlap) return fail(res, 409, "SCHEDULE_CONFLICT", "Huấn luyện viên đã có lịch trong khung giờ này"); const schedule = { id: gymStore.nextId("schedules"), ...parsed.data }; gymStore.schedules.push(schedule); gymStore.log(req.user!.id, "CREATE", "schedules", schedule.id); return created(res, schedule); });
api.patch("/schedules/:id", allow("admin", "trainer"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const parsed = scheduleInput.partial().safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu cập nhật không hợp lệ", parsed.error.issues); const schedule = gymStore.schedules.find(item => item.id === id); if (!schedule) return fail(res, 404, "NOT_FOUND", "Không tìm thấy lịch tập"); const next = { ...schedule, ...parsed.data }; if (!validWindow(next.startAt, next.endAt)) return fail(res, 400, "INVALID_TIME_WINDOW", "Thời gian bắt đầu phải trước thời gian kết thúc"); if (!trainerScope(req, res, next.trainerId)) return; const overlap = gymStore.schedules.some(item => item.id !== id && item.trainerId === next.trainerId && item.status === "scheduled" && new Date(next.startAt) < new Date(item.endAt) && new Date(next.endAt) > new Date(item.startAt)); if (overlap) return fail(res, 409, "SCHEDULE_CONFLICT", "Huấn luyện viên đã có lịch trong khung giờ này"); Object.assign(schedule, parsed.data); gymStore.log(req.user!.id, "UPDATE", "schedules", id); return ok(res, schedule); });
api.delete("/schedules/:id", allow("admin", "trainer"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const schedule = gymStore.schedules.find(item => item.id === id); if (!schedule) return fail(res, 404, "NOT_FOUND", "Không tìm thấy lịch tập"); if (req.user?.role === "trainer" && trainerIdForUser(req.user) !== schedule.trainerId) return fail(res, 403, "FORBIDDEN", "Trainer chỉ được xóa lịch của chính mình"); const index = gymStore.schedules.findIndex(item => item.id === id); gymStore.schedules.splice(index, 1); gymStore.log(req.user!.id, "DELETE", "schedules", id); return res.status(204).send(); });

api.get("/checkins", allow("admin", "member"), (req: AuthedRequest, res) => { const query = pageQuery.parse(req.query); let rows = gymStore.checkins.map(item => ({ ...item, member: gymStore.members.find(member => member.id === item.memberId) })); if (req.user?.role === "member") rows = rows.filter(item => item.memberId === req.user!.memberId); if (query.search) rows = rows.filter(item => item.member?.name.toLowerCase().includes(query.search!.toLowerCase())); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/checkins/summary", allow("admin"), (_req, res) => ok(res, { today: gymStore.dashboard().todayCheckins, currentlyInside: gymStore.checkins.filter(item => !item.checkOutAt).length, averageMinutes: Math.round(gymStore.checkins.filter(item => item.durationMinutes).reduce((sum, item) => sum + (item.durationMinutes || 0), 0) / Math.max(1, gymStore.checkins.filter(item => item.durationMinutes).length)) }));
api.get("/checkins/:id", allow("admin", "member"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const item = gymStore.checkins.find(checkin => checkin.id === id); if (!item) return fail(res, 404, "NOT_FOUND", "Không tìm thấy lượt check-in"); if (req.user?.role === "member" && item.memberId !== req.user.memberId) return fail(res, 403, "FORBIDDEN", "Bạn chỉ được xem lượt check-in của mình"); return ok(res, { ...item, member: gymStore.members.find(member => member.id === item.memberId) }); });
api.post("/checkins", allow("admin"), (req: AuthedRequest, res) => { const parsed = z.object({ memberId: z.coerce.number().int().positive() }).safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Hội viên không hợp lệ"); const member = gymStore.members.find(item => item.id === parsed.data.memberId); const membership = member && gymStore.getMemberMembership(member.id); const today = new Date().toISOString().slice(0, 10); if (!member || member.status !== "active" || !membership || membership.status !== "active" || membership.startDate > today || membership.endDate < today) return fail(res, 409, "MEMBERSHIP_REQUIRED", "Hội viên chưa có gói tập còn hiệu lực"); if (gymStore.checkins.some(item => item.memberId === member.id && !item.checkOutAt)) return fail(res, 409, "ALREADY_CHECKED_IN", "Hội viên đang ở trong phòng tập"); const checkin = { id: gymStore.nextId("checkins"), memberId: member.id, checkInAt: new Date().toISOString(), recordedBy: req.user!.id }; gymStore.checkins.unshift(checkin); gymStore.log(req.user!.id, "CREATE", "checkins", checkin.id); return created(res, { ...checkin, member }); });
api.patch("/checkins/:id/checkout", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const checkin = gymStore.checkins.find(item => item.id === id); if (!checkin) return fail(res, 404, "NOT_FOUND", "Không tìm thấy lượt check-in"); if (checkin.checkOutAt) return fail(res, 409, "ALREADY_CHECKED_OUT", "Lượt check-in đã được check-out"); const checkOutAt = new Date(); if (checkOutAt.getTime() < new Date(checkin.checkInAt).getTime()) return fail(res, 409, "INVALID_CHECKOUT_TIME", "Thời gian check-out không hợp lệ"); checkin.checkOutAt = checkOutAt.toISOString(); checkin.durationMinutes = Math.max(1, Math.round((checkOutAt.getTime() - new Date(checkin.checkInAt).getTime()) / 60000)); gymStore.log(req.user!.id, "CHECKOUT", "checkins", id); return ok(res, checkin); });

api.get("/payments", allow("admin", "member"), (req: AuthedRequest, res) => { const query = pageQuery.parse(req.query); let rows = gymStore.payments.map(item => ({ ...item, member: gymStore.members.find(member => member.id === item.memberId) })); if (req.user?.role === "member") rows = rows.filter(item => item.memberId === req.user!.memberId); if (query.search) rows = rows.filter(item => `${item.reference} ${item.member?.name}`.toLowerCase().includes(query.search!.toLowerCase())); if (query.status) rows = rows.filter(item => item.status === query.status); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/payments/:id", allow("admin", "member"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const item = gymStore.payments.find(payment => payment.id === id); if (!item) return fail(res, 404, "NOT_FOUND", "Không tìm thấy thanh toán"); if (req.user?.role === "member" && item.memberId !== req.user.memberId) return fail(res, 403, "FORBIDDEN", "Bạn chỉ được xem thanh toán của mình"); return ok(res, { ...item, member: gymStore.members.find(member => member.id === item.memberId) }); });
const paymentInput = z.object({ memberId: z.coerce.number().int().positive(), membershipId: z.coerce.number().int().positive().optional(), amount: z.coerce.number().positive(), method: z.enum(["cash", "transfer", "card"]), status: z.enum(["paid", "pending", "refunded"]).default("paid") });
api.post("/payments", allow("admin"), (req: AuthedRequest, res) => { const parsed = paymentInput.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu thanh toán không hợp lệ", parsed.error.issues); const member = gymStore.members.find(item => item.id === parsed.data.memberId); if (!member) return fail(res, 404, "NOT_FOUND", "Không tìm thấy hội viên"); if (parsed.data.membershipId) { const membership = gymStore.memberships.find(item => item.id === parsed.data.membershipId); if (!membership || membership.memberId !== member.id) return fail(res, 409, "MEMBERSHIP_MISMATCH", "Membership không thuộc hội viên này"); } const payment = { id: gymStore.nextId("payments"), ...parsed.data, reference: `GF-${new Date().getFullYear()}-${String(gymStore.nextIds.payments - 1).padStart(4, "0")}`, paidAt: new Date().toISOString(), createdBy: req.user!.id }; gymStore.payments.unshift(payment); gymStore.log(req.user!.id, "CREATE", "payments", payment.id); return created(res, { ...payment, member }); });
api.patch("/payments/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const parsed = z.object({ status: z.enum(["paid", "pending", "refunded"]) }).safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Trạng thái thanh toán không hợp lệ"); const payment = gymStore.payments.find(item => item.id === id); if (!payment) return fail(res, 404, "NOT_FOUND", "Không tìm thấy thanh toán"); payment.status = parsed.data.status; return ok(res, payment); });

api.get("/users", allow("admin"), (req, res) => { const query = pageQuery.parse(req.query); let rows = gymStore.users.map(({ password, ...user }) => user); if (query.search) rows = rows.filter(item => `${item.name} ${item.email}`.toLowerCase().includes(query.search!.toLowerCase())); if (query.status) rows = rows.filter(item => item.role === query.status); const result = paginate(rows, query); return ok(res, result.rows, result.meta); });
api.get("/users/:id", allow("admin"), (req, res) => { const id = parseId(req, res); if (!id) return; const user = gymStore.users.find(item => item.id === id); if (!user) return fail(res, 404, "NOT_FOUND", "Không tìm thấy người dùng"); const { password, ...safeUser } = user; return ok(res, safeUser); });
const userInput = z.object({ name: z.string().min(2), email: z.string().email(), password: z.string().min(6), role: z.enum(["admin", "trainer"]) });
api.post("/users", allow("admin"), (req: AuthedRequest, res) => { const parsed = userInput.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu người dùng không hợp lệ", parsed.error.issues); if (gymStore.users.some(item => item.email === parsed.data.email)) return fail(res, 409, "EMAIL_EXISTS", "Email đã tồn tại"); const user = { id: gymStore.nextId("users"), ...parsed.data, avatar: parsed.data.name.split(" ").map(part => part[0]).slice(-2).join("").toUpperCase() }; gymStore.users.push(user); return created(res, { ...user, password: undefined }); });
api.patch("/users/:id", allow("admin"), (req: AuthedRequest, res) => { const id = parseId(req, res); if (!id) return; const parsed = userInput.partial().safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Dữ liệu cập nhật không hợp lệ", parsed.error.issues); const user = gymStore.users.find(item => item.id === id); if (!user) return fail(res, 404, "NOT_FOUND", "Không tìm thấy người dùng"); if (parsed.data.email && gymStore.users.some(item => item.id !== id && item.email.toLowerCase() === parsed.data.email!.toLowerCase())) return fail(res, 409, "EMAIL_EXISTS", "Email đã được dùng cho tài khoản khác"); Object.assign(user, parsed.data); if (user.memberId) { const member = gymStore.members.find(item => item.id === user.memberId); if (member) { member.name = user.name; member.email = user.email; } } const { password, ...safeUser } = user; return ok(res, safeUser); });
api.delete("/users/:id", allow("admin"), (req, res) => { const id = parseId(req, res); if (!id) return; if (id === 1) return fail(res, 409, "PROTECTED_USER", "Không thể xóa tài khoản admin mặc định"); const index = gymStore.users.findIndex(item => item.id === id); if (index < 0) return fail(res, 404, "NOT_FOUND", "Không tìm thấy người dùng"); if (gymStore.users[index].memberId) return fail(res, 409, "MEMBER_ACCOUNT_LINKED", "Hãy quản lý tài khoản qua hồ sơ hội viên"); gymStore.users.splice(index, 1); return res.status(204).send(); });

api.get("/audit-logs", allow("admin"), (_req, res) => ok(res, gymStore.auditLogs.slice(0, 50)));
api.use((err: unknown, _req: Request, res: Response, _next: NextFunction) => { console.error("[REST API]", err); if (err instanceof z.ZodError) return fail(res, 400, "VALIDATION_ERROR", "Query hoặc dữ liệu request không hợp lệ", err.issues); return fail(res, 500, "INTERNAL_ERROR", "Đã xảy ra lỗi máy chủ"); });
export function createGymApiRouter() { return api; }
